### PR TITLE
ACI: Allow setting protocol when publishing ports

### LINKED ISSUE #985: ACI: 'run' command fails to create UDP protocol binding for public IP address
**Steps to reproduce the issue:**
1. Create ACI Docker context e.g. 'acictx'
2. `docker --context acictx run -d -p 12345/udp some-udp-based-network-service-image`

**Describe the results you received:**
No errors/warnings, but the public IP address created as part of the ACI container group is using TCP protocol

**Describe the results you expected:**
The public IP address created as part of the ACI container group should use UDP protocol

**Additional information you deem important (e.g. issue happens only occasionally):**
You can verify the protocol used by the IP address with Azure CLI (`az container show`). Deploying via `az container create` works as expected (UDP protocol binding is created and communication works).

Tried on Docker Desktop for Mac 2.5.2 (50156). Also tried on Ubuntu Linux with the same effect.

### PR DESCRIPTION
**Pull request by gtardif**
Signed-off-by: Guillaume Tardif <guillaume.tardif@gmail.com>

**What I did**
* Add protocol conversion when creating ACI container group for tcp/udp
* deploy and check runtime `docker inspect` also returns the correct port protocol.
* added an error for unknown protocols

**Related issue**
Fixes #985 

/test-aci

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**

### CODE REVIEW

File: aci/convert/ports.go [hunk 1]
```diff
@@ -37,12 +37,25 @@ func convertPortsToAci(service serviceConfigAciHelper) ([]containerinstance.Cont
...
+		var containerProtocol containerinstance.ContainerNetworkProtocol
+		switch portConfig.Protocol {
+		case "tcp", "":
+			groupProtocol = containerinstance.TCP
+			containerProtocol = containerinstance.ContainerNetworkProtocolTCP
+		case "udp":
+			groupProtocol = containerinstance.UDP
+			containerProtocol = containerinstance.ContainerNetworkProtocolUDP
+		default:
+			return nil, nil, nil, fmt.Errorf("Unknown protocol %q in exposed port for service %q", portConfig.Protocol, service.Name)
```
Comment (rumpl) [inline aci/convert/ports.go:50]:
```suggestion
			return nil, nil, nil, fmt.Errorf("unknown protocol %q in exposed port for service %q", portConfig.Protocol, service.Name)
```

Comment (gtardif) [reply aci/convert/ports.go]: ... can't put this in my head ! :) fixed

**Comment by karolz-ms** [comment]
☺️ thank you @gtardif

**Review by rumpl — APPROVED** [review]

**Review by ndeloof — APPROVED** [review]
