### PR TITLE
Fix metrics flakyness

### LINKED ISSUE #1033: Flaky test on metrics gathering
Probably due to some timing, I've seen this a couple of times already: 
```
http server started on /tmp/195461985/docker-cli.sock
	[TestContextMetrics] docker --help
	[TestContextMetrics] docker run --help
Error:     e2e_test.go:155: assertion failed: 
        --- ←
        +++ usage
          []string{
        - 	`{"command":"help run","context":"moby","source":"cli","status":"success"}`,
          	`{"command":"--help","context":"moby","source":"cli","status":"su`...,
          	`{"command":"--help run","context":"moby","source":"cli","status"`...,
          }
```
https://github.com/docker/compose-cli/pull/1032/checks?check_run_id=1518710270

### PR DESCRIPTION
**Pull request by gtardif**
**What I did**
* cleanup previous fix (#1038) that didn't correct the root cause
* realised the metrics mock server was started totally async, need to wait a bit
* could not find an easy API to check the server is ready, wait for 500 ms, other solutions would loop and wait anyway... 

**Related issue**
Fixes #1033 

**(not mandatory) A picture of a cute animal, if possible in relation with what you did**

### CODE REVIEW

**Comment by gtardif** [comment]
Actually it seems it does not fully work (also debugging this in a loop: https://github.com/gtardif/compose-cli/runs/1571246788?check_suite_focus=true). I'll add a proper wait loop checking we receive a first metric

**Comment by gtardif** [comment]
And running this in loop, green (https://github.com/gtardif/compose-cli/runs/1571545817?check_suite_focus=true ; needed to run all E2E tests to reproduce the issue, not only the metrics one)

File: tests/e2e/e2e_test.go [hunk 1]
```diff
@@ -144,14 +144,26 @@ func TestContextMetrics(t *testing.T) {
 	s.Start()
 	defer s.Stop()
 
+	started := false
+	for i := 0; i < 30; i++ {
```
Comment (ndeloof) [inline tests/e2e/e2e_test.go:148]: Let me play the Gopher pursist for once :P

`NewMetricsServer.Start` could return a `chan bool` and send `true` when ready, then test can wait on `<- start`

LGTM otherwise

**Review by ndeloof — APPROVED** [review]

File: tests/e2e/e2e_test.go (hunk 1 above)
Comment (gtardif) [reply tests/e2e/e2e_test.go:148]: yes, but then we need "c" to run commands in Start... (Start could also just wait before returning)
